FROM node:24-alpine

WORKDIR /workspace
RUN corepack enable
COPY . .
RUN pnpm install --frozen-lockfile && pnpm generate:api && pnpm --filter @bookipi/backend build

EXPOSE 3001
CMD ["pnpm", "--filter", "@bookipi/backend", "start"]
