openapi: 3.1.0
info:
  title: Bookipi backend API
  version: 1.0.0
paths:
  /api/system/health:
    $ref: ./system/openapi.yml#/paths/~1health
  /api/listings/{listingId}:
    $ref: ./listings/get-listing/openapi.yml#/paths/~1listings~1{listingId}
  /api/orders/{orderId}:
    $ref: ./orders/get-order/openapi.yml#/paths/~1orders~1{orderId}
  /api/orders/current:
    $ref: ./orders/get-order-for-listing/openapi.yml#/paths/~1orders~1current
  /api/orders/{orderId}/payment-outcome:
    $ref: ./orders/post-payment-outcome/openapi.yml#/paths/~1orders~1{orderId}~1payment-outcome
x-groups:
  - ./system/openapi.yml
  - ./listings/openapi.yml
  - ./orders/openapi.yml
